[package]
name = "csloc"
version = "0.1.0"
authors = ["lemonxah <lemon.xah@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "2.33.0", features = ["yaml"]}
walkdir = "2"
funlib = "0.1.7"